"""
cold_probe.py — tests whether the InFlight NLX API works with pure requests,
zero Playwright. Requires nlx_body.txt (generated by api_probe.py).

Flow:
  1. requests.Session() GET the event page  →  establishes InFlightSessionID
  2. POST to the NLX API with the saved template body
  3. Follow the 278 IFLocation redirect
  4. Parse and print extracted fields

Run:
  python api_probe.py   # generates nlx_body.txt if not present
  python cold_probe.py
"""

import json
import requests
from pathlib import Path
from scraper import build_url, load_xls

NLX_BASE = (
    "https://caleprocure.ca.gov/nlx3/psc/psfpd1_newwin"
    "/SUPPLIER/ERP/c/AUC_MANAGE_BIDS.AUC_RESP_INQ_DTL.GBL"
)
FIXED_PARAMS = {
    "Page":         "AUC_RESP_INQ_DTL",
    "Action":       "U",
    "AUC_ROUND":    "1",
    "BIDDER_ID":    "BID0000001",
    "BIDDER_LOC":   "1",
    "BIDDER_SETID": "STATE",
    "BIDDER_TYPE":  "B",
}
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)


def nlx_post(session, event_url, event_id, dept, body):
    """POST to the NLX API, follow the 278 redirect, return parsed JSON."""
    params = {**FIXED_PARAMS, "AUC_ID": event_id, "BUSINESS_UNIT": dept}
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Referer": event_url,
        "Origin": "https://caleprocure.ca.gov",
    }
    resp = session.post(NLX_BASE, params=params, data=body, headers=headers, timeout=30)

    if resp.status_code == 278:
        location = resp.json().get("IFLocation", "")
        if location.startswith("/"):
            location = "https://caleprocure.ca.gov" + location
        resp = session.post(location, data=body, headers=headers, timeout=30)

    resp.raise_for_status()
    return resp.json().get("CaptureResults", {})


def leaf(nodes):
    if nodes:
        props = nodes[0].get("Properties", {})
        return props.get("text") or props.get("html") or ""
    return ""


def main():
    body_path = Path("nlx_body.txt")
    if not body_path.exists():
        print("nlx_body.txt not found — run api_probe.py first to generate it.")
        return
    body = body_path.read_text()

    df = load_xls()
    row = df.iloc[0]
    dept_col, id_col = df.columns[0], df.columns[2]

    try:
        dept = str(int(row[dept_col])).zfill(4)
    except (ValueError, TypeError):
        dept = str(row[dept_col]).strip()
    event_id  = str(row[id_col])
    event_url = build_url(row[dept_col], event_id)
    print(f"Probe event: {event_url}\n")

    session = requests.Session()
    session.headers.update({"User-Agent": UA})

    # ── Step 1: GET the event page to establish InFlightSessionID ─────────────
    print("Step 1: GET event page to establish session cookies...")
    resp = session.get(event_url, timeout=20)
    print(f"  Status: {resp.status_code}")

    inf = session.cookies.get("InFlightSessionID")
    asp = session.cookies.get("ASP.NET_SessionId")
    print(f"  InFlightSessionID : {inf or '(not set)'}")
    print(f"  ASP.NET_SessionId : {asp or '(not set)'}")

    if not inf:
        print("\nWARNING: InFlightSessionID was not set — the API call may fail.")

    # ── Step 2: POST to NLX API ───────────────────────────────────────────────
    print("\nStep 2: POSTing to NLX API...")
    try:
        results = nlx_post(session, event_url, event_id, dept, body)
    except Exception as e:
        print(f"  FAILED: {e}")
        return
    print("  OK")

    # ── Step 3: print extracted fields ────────────────────────────────────────
    print("\nStep 3: Extracted fields:")
    scalar_fields = {
        "event_version":    leaf(results.get("eventVersion")),
        "published_date":   leaf(results.get("eventStartDate")),
        "contact_phone":    leaf(results.get("phoneText")),
        "prebid_mandatory": leaf(results.get("conferenceText")),
        "description":      leaf(results.get("descriptiondetails")),
    }
    for k, v in scalar_fields.items():
        print(f"  {k:<20} {str(v)[:80]}")

    unspsc_rows = results.get("unspscCodeBody", [])
    print(f"\n  unspscCodeBody rows: {len(unspsc_rows)}")
    for r in unspsc_rows[:3]:
        ch = r.get("Children", {})
        code = leaf(ch.get("unspscClassification", []))
        desc = leaf(ch.get("unspscDescription", []))
        if code:
            print(f"    {code}: {desc[:70]}")

    sa_rows = results.get("serviceAreaTblBody", [])
    print(f"\n  serviceAreaTblBody rows: {len(sa_rows)}")
    for r in sa_rows[:5]:
        ch = r.get("Children", {})
        print(f"    {leaf(ch.get('serviceAreaID', []))}: {leaf(ch.get('serviceAreaCounty', []))}")

    print("\n── Result ──────────────────────────────────────────────────────────────")
    if scalar_fields["description"] and len(sa_rows) > 0:
        print("SUCCESS — cold requests works. Playwright can be removed entirely.")
    else:
        print("PARTIAL — session established but data missing. May need further investigation.")


if __name__ == "__main__":
    main()
